gitSourceBranch = "main"
gitRepoUrl = "https://github.com/Breezy1214/PathWatcher"

[home]
enabled = true
includeReadme = false

[docusaurus]
projectName = "PathWatcher"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
tagline = "Reactive path observation for Fusion with efficient delta-based change detection"
